### ISSUE TITLE
Out-of-gas attack

### ISSUE THREAD

**Issue by adria0** [Giveth/vaultcontroller#11]
An hostile child vault administrator can create multiple child vaults/subvaults in order to make rootVault.cancelVault() unusable becasue always gets out of gas.

**Comment by jbaylina** [comment]
This is fixed.
The way of solving is that I limit the number of childs, the number of hierachies and the cancel is a multistep process if there is not enough gas to cancel all. 

There is a specific test `big_cancel_all` to test this functionality.
