### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by adria0** [Giveth/vaultcontroller#12]
Consider change `86400` for `24 hours`

**Comment by jbaylina** [comment]
As the contract always works in seconds, I lite to put this in seconds too.

**Comment by GriffGreen** [comment]
I like seconds (make 24 hours a comment)

**Comment by dipenjoshi** [comment]
seconds its is.

**Comment by adria0** [comment]
hours is a solidity emeeded alias for  3600 since solidity works always with seconds. So we still will be working with seconds.
