### ISSUE TITLE
Add isInitialized()

### ISSUE THREAD

**Issue by adria0** [Giveth/vaultcontroller#14]
It's not usual to use an external property with different semantics (address(childVault) == 0) that the propery name says. Maybe is usefull to add a function like `isInitialized()` for this:
  
Instead:

```
function topUpVault() initialized notCanceled {
        ...
        Vault childVault = Vault(vc.primaryVault());
        if (address(childVault) == 0) throw; // Child project is not initialized
        ...
}
```

use

```
function topUpVault() initialized notCanceled {
        ...
        if (!vc.isInitialized())  throw;
        Vault childVault = Vault(vc.primaryVault());
        ...
}
```

**Comment by jbaylina** [comment]
Your optios takes two calls instead of one and needs an extra method. (We need to safe gas in the deployment).
