### ISSUE TITLE
2 comments and 43 name changes :-)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontroller#2]
A couple of comments:

sendBackOverflow needs to be checked... or explained to me... it seems like it only works for the primary vault...?

The Cancel projects stuff doesn't make sense... I'm excited to see what it looks like once you attack it :-) 

SO MANY NAME CHANGES

1. ProjectController = VaultController

2. activationTime = timeLockExpiration  

3. dailyLimit = dailyValueLimit

4. dailyTransactions = dailyTxnLimit

5. transactionLimit = txnValueLimit

6. startHour = openingTime

7. endHour = closingTime

8. addr2recipient = addr2recipientID

9.  addr2spender = addr2spenderID

 10. childProjects = childVaultControllers

11.  addr2project = addr2VaultControllerID

12. parentProjectController = parentVaultController

13. mainVault = primaryVault

14. projectControllerFactory = vaultControllerFactory

15. topThreshold = highestAcceptableBalance 

16. bottomThreshold = lowestAcceptableBalance

17. maxDailyLimit = maxDailyValueLimit

18. maxDailyTransactions = maxDailyTxnLimit

19. maxTransactionLimit = maxTxnValueLimit

20. maxTopThreshold = maxHighestAcceptableBalance

21. createProject = createVaultController

22. cancelChildProject = cancelChildVault

23. cancelProject = cancelVault

24. setProjectParams = setVaultLimits

25. refillMe = topUpVault

26. idProject = idVault

27. projectBalance = vaultBalance

28. newPayment = sendToAuthorizedRecipient

29. unauthorizeSpender = removeAuthorizedSpender

30. unauthorizeRecipient = removeAuthorizedRecipient

31. actualHour = actualTime

32. timeSinceStart = timeSinceOpening

33. numberOfProjects = numberOfVaults

34. event AuthorizedRecipient = RecipientAuthorized

35. event UnauthorizedRecipient = RemoveAuthorizedRecipient

36. uint indexed idSpender, address indexed recipient = uint indexed idRecipient, address indexed recipient

37. event AuthorizeSpender = SpenderAuthorized

38. event UnauthorizeSpender = RemoveAuthorizedSpender

39. event NewProject = NewVault

40. event ProjectCanceled = VaultCanceled

41. event ProjectRefill =  TopUpVault

42. event ParamsChanged = VaultLimitsChanged

43. contract ProjectControllerFactory = VaultControllerFactory

**Comment by jbaylina** [comment]
Done!
