### ISSUE TITLE
Parent Vault == 0x0 burns ether when overflow

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontroller#21]
There should be a check to make sure the parent vault is never 0x0 :-D Oops! Bad documentation!!

**Comment by GriffGreen** [comment]
We need checks on `sendBackOverflow()`
and `create()`

**Comment by GriffGreen** [comment]
We should also change the name of ParentVault to parentAddress

**Comment by jbaylina** [comment]
The check to 0x0 is done!

Pleas, Put different issues in different threads.
