### ISSUE TITLE
Re-authorizing an existent recipient does not fail if names are not equal

### ISSUE THREAD

**Issue by adria0** [Giveth/vaultcontroller#33]
```
vaultController.authorizeRecipient(spender,recipient,"NAME2")
```
does not fail if

```
vaultController.authorizeRecipient(spender,recipient,"NAME1")
```

 was added before

**Comment by jbaylina** [comment]
Fixed!

**Comment by adria0** [comment]
@jbaylina I still have this issue with the current code.

**Comment by jbaylina** [comment]
I follow the same philosophy. (We may want to change it). If you add a recipient that it's added, it just do nothing. 
The difference is that now it does not duplicate entries.

**Comment by adria0** [comment]
Ok! We should document that, then.
