### ISSUE TITLE
name changes and a request to review :-)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontroller#5]
initialize = initializeVault

createVaultController = createChildVaultController

pc = vc

initializeChildVaultController = initializeChildVault

_idVault = _vaultControllerId

cancelVaultController = cancelVault

addAuthorizeSpender = authorizeSpender

addr2dpenderId = addr2spenderId

function sendToAuthorizedRecipient needs to be checked in general... not sure if its supposed to do idSpender --; or at least i need this explained

**Comment by jbaylina** [comment]
Done!
